###注册 中心
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9999/eureka/
#  instance:
#    hostname: device
#    prefer-ip-address: true
###网关名称
spring:
  application:
    name: mvmp-zuul
  rabbitmq:
    username: guest
    password: guest
    host: 123.57.13.249
    port: 5672
#  cloud:
#    config:
#      ####读取后缀
#      profile: dev
#      ####读取config-server注册地址
#      discovery:
#        service-id: config-server
#        enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
#### 配置服务路由，注意命名规则:path属性为: /api-*/*;serviceId属性为: *-*-service
zuul:
  routes:
    api-user:
      ### 以 /api-user/访问转发到用户相关接口
      path: /api-user/**
      serviceId: user-manager-service
    api-driver:
      ### 以 /api-driver/访问转发到司机相关接口
      path: /api-driver/**
      serviceId: driver-manager-service